### ISSUE TITLE
file_utils >=0.1.2 depends on path ^1.6.4

### ISSUE THREAD

**Issue by Respect-M** [mezoni/file_utils#2]
flutter_driver from sdk depends on path 1.6.2 and file_utils >=0.1.2 depends on path ^1.6.4, flutter_driver from sdk is incompatible with file_utils >=0.1.2.
So, because gobills_app depends on both file_utils ^0.1.2 and flutter_driver any from sdk, version solving failed

**Comment by mezoni** [comment]
What is your suggestions?
Specify the path version as `any`?

**Comment by mezoni** [comment]
https://github.com/mezoni/file_utils/commit/21d5cdf84653fcceebccc2bbd69209d5a4a0736c
0.1.3
Return to the old version (^1.6.2) of the package dependency "path"

So will it work?
