### ISSUE TITLE
Lacking 'copy' method

### ISSUE THREAD

**Issue by sharpsan** [mezoni/file_utils#3]
Seeing as how there is a 'move' method, a 'copy' method would be useful.

**Comment by mezoni** [comment]
Hello.
Thank you for your interest.
This package mainly offers those features that are not (or were not previously) in the package `dart:io`.

It is unlikely that there will be more benefit if duplicating existing features.

An example of copying a file.

````dart
import 'dart:io';

void main() {
  final file = File('abc.txt');
  final newPath = 'def.txt';
  file.copySync(newPath);
}
````

In the case of a move, you only need to add its deletion.

```dart
file.deleteSync();`
```

Short code:

````dart
File('abc.txt').copySync('def.txt').delete();
```

**Comment by sharpsan** [comment]
Got it, thank you for the explanation.
